name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dart_frog:
  dart_frog_web_socket:
  dart_jsonwebtoken:
  dbcrypt:
  mysql_client:

dev_dependencies:
  mocktail:
  test:
  very_good_analysis:
